# Python CircleCI 2.0 config file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9.5

    working_directory: ~/repo

    steps:
      # step 1: obtain repo from github
      - checkout
      # step 2: setup the environment
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            .venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt
      # step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator